# Generated by Django 5.1.4 on 2026-05-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exercise_guidelines_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
