# Generated by Django 5.1.4 on 2026-05-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exercise_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'poses',
            },
        ),
    ]
